"""Frozen-development, exact-feature-grouped CPU/GPU comparison for KAMP task 01.

No old holdout is read for fitting, selection, or metric reporting. The score is
for numeric PassOrFail=1; its physical defect meaning is not yet established.
GPU execution requires an independently verified task-04 ZIP receipt.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.metadata
import json
import platform
import subprocess
import sys
import zipfile
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier
from sklearn.metrics import brier_score_loss, log_loss
from xgboost import XGBClassifier

import calibration_diagnostics as cd
import moldguard as mg


ROOT = Path(__file__).resolve().parent
SEEDS = (20260922, 20260923, 20260924)
CONDITIONS = ("Clamp_Close_Time", "Max_Injection_Pressure", "Max_Switch_Over_Pressure")
CPU_MODELS = ("logistic_ref", "lgbm_shallow", "lgbm_regularized", "xgb_shallow", "xgb_regularized", "catboost_ref", "catboost_regularized")
GPU_MODELS = ("xgb_shallow", "xgb_regularized", "catboost_ref", "catboost_regularized")


def write_json(path: Path, value: object) -> None:
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2, allow_nan=False) + "\n", encoding="utf-8")


def check_gpu_receipt(path: Path | None) -> dict:
    """Refuse GPU work until the task-04 result archive is locally recovered.

    The receipt is prepared only after a human verifies the complete archive.
    It is not generated by this task-01 program.
    """
    if path is None or not path.is_file():
        raise ValueError("GPU_BLOCKED: --task04-receipt JSON is required after task-04 ZIP recovery")
    receipt = json.loads(path.read_text(encoding="utf-8"))
    if receipt.get("task04_results_recovered") is not True:
        raise ValueError("GPU_BLOCKED: task-04 result recovery is not confirmed")
    archive = Path(receipt.get("task04_zip", ""))
    expected = receipt.get("sha256")
    if not archive.is_file() or not isinstance(expected, str) or len(expected) != 64:
        raise ValueError("GPU_BLOCKED: task-04 ZIP path or SHA-256 is invalid")
    if archive.suffix.lower() != ".zip" or mg.sha256(archive) != expected:
        raise ValueError("GPU_BLOCKED: task-04 ZIP hash does not match")
    try:
        with zipfile.ZipFile(archive) as bundle:
            if not bundle.namelist() or bundle.testzip() is not None:
                raise ValueError("GPU_BLOCKED: task-04 ZIP is empty or has a failed CRC")
    except zipfile.BadZipFile as error:
        raise ValueError("GPU_BLOCKED: task-04 ZIP is corrupt") from error
    if not receipt.get("verified_at_utc") or not receipt.get("verified_by"):
        raise ValueError("GPU_BLOCKED: receipt needs verification time and verifier")
    return {"task04_zip": str(archive.resolve()), "sha256": expected,
            "verified_at_utc": receipt["verified_at_utc"], "verified_by": receipt["verified_by"]}


def check_gpu_runtime() -> dict:
    if platform.system() != "Linux":
        raise RuntimeError("GPU_BLOCKED: this overnight package requires a Linux NVIDIA runtime")
    result = subprocess.run(["nvidia-smi", "--query-gpu=name,driver_version,memory.total",
                             "--format=csv,noheader"], capture_output=True, text=True, check=False)
    if result.returncode or not result.stdout.strip():
        raise RuntimeError("GPU_BLOCKED: nvidia-smi did not find a usable NVIDIA GPU")
    return {"nvidia_smi": result.stdout.strip()}


def make_candidate(name: str, seed: int, device: str, y_train: np.ndarray):
    if name == "logistic_ref":
        if device != "cpu":
            raise ValueError("Logistic reference is CPU only")
        return mg.make_model("logistic")
    if name.startswith("lgbm_"):
        if device != "cpu":
            raise ValueError("LightGBM GPU build is not included in this package")
        params = dict(objective="binary", n_jobs=4, random_state=seed, verbosity=-1,
                      deterministic=True, force_col_wise=True, is_unbalance=True)
        if name == "lgbm_shallow":
            params.update(n_estimators=350, learning_rate=.03, max_depth=3,
                          num_leaves=7, min_child_samples=20, reg_lambda=5)
        elif name == "lgbm_regularized":
            params.update(n_estimators=500, learning_rate=.025, max_depth=5,
                          num_leaves=15, min_child_samples=35, reg_lambda=10,
                          colsample_bytree=.8)
        else:
            raise ValueError(name)
        return LGBMClassifier(**params)
    if name.startswith("xgb_"):
        ratio = float((len(y_train) - y_train.sum()) / y_train.sum())
        params = dict(objective="binary:logistic", eval_metric="logloss", tree_method="hist",
                      device="cuda" if device == "gpu" else "cpu", n_jobs=4,
                      random_state=seed, scale_pos_weight=ratio, verbosity=0)
        if name == "xgb_shallow":
            params.update(n_estimators=350, learning_rate=.03, max_depth=2,
                          min_child_weight=5, reg_lambda=10)
        elif name == "xgb_regularized":
            params.update(n_estimators=500, learning_rate=.025, max_depth=3,
                          min_child_weight=10, reg_lambda=20, subsample=.8,
                          colsample_bytree=.8)
        else:
            raise ValueError(name)
        return XGBClassifier(**params)
    if name.startswith("catboost_"):
        params = dict(loss_function="Logloss", auto_class_weights="Balanced",
                      random_seed=seed, task_type="GPU" if device == "gpu" else "CPU",
                      thread_count=4, verbose=False, allow_writing_files=False)
        if name == "catboost_ref":
            params.update(iterations=400, depth=4, learning_rate=.03, l2_leaf_reg=5)
        elif name == "catboost_regularized":
            params.update(iterations=600, depth=5, learning_rate=.025, l2_leaf_reg=10)
        else:
            raise ValueError(name)
        return CatBoostClassifier(**params)
    raise ValueError(name)


def validate_frozen_data() -> tuple[pd.DataFrame, pd.DataFrame, dict]:
    data, features, provenance = cd.load_development()
    frozen = pd.read_csv(cd.FROZEN / "split_manifest.csv")
    if len(data) != int(frozen.partition.eq("development").sum()):
        raise ValueError("Frozen development row count differs")
    if set(data.feature_group) & set(frozen.loc[frozen.partition.eq("holdout"), "feature_group"]):
        raise ValueError("Exact-feature group leakage into holdout")
    if data.groupby("feature_group").outer_fold.nunique().max() != 1:
        raise ValueError("Exact-feature group crosses OOF folds")
    if set(data.outer_fold) != set(range(5)):
        raise ValueError("Expected frozen folds 0..4")
    if any(data.loc[data.outer_fold.eq(f), mg.TARGET].sum() == 0 for f in range(5)):
        raise ValueError("Each validation fold needs a positive example")
    x = mg.feature_matrix(data, features)
    if not np.isfinite(x.to_numpy(dtype=float)).all():
        raise ValueError("Invalid features")
    return data, x, provenance


def score(y: np.ndarray, probability: np.ndarray) -> dict:
    if not np.isfinite(probability).all() or np.any((probability < 0) | (probability > 1)):
        raise ValueError("Invalid or incomplete score")
    return {**mg.score_metrics(y, probability),
            "brier_unadjusted": float(brier_score_loss(y, probability)),
            "log_loss_unadjusted": float(log_loss(y, probability, labels=[0, 1]))}


def run(device: str, output: Path, receipt: Path | None) -> None:
    if output.exists():
        raise FileExistsError(f"Never overwrite a prior run: {output}")
    gpu_receipt, gpu_runtime = None, None
    if device == "gpu":
        gpu_receipt = check_gpu_receipt(receipt)
        gpu_runtime = check_gpu_runtime()
    data, x, provenance = validate_frozen_data()
    models = GPU_MODELS if device == "gpu" else CPU_MODELS
    output.mkdir(parents=True)
    started = datetime.now(timezone.utc).isoformat()
    y = data[mg.TARGET].to_numpy(dtype=int)
    prediction_rows, metric_rows, fold_rows, condition_rows = [], [], [], []
    for model_name in models:
        for seed in SEEDS:
            predictions = np.full(len(data), np.nan)
            for fold in range(5):
                train = data.outer_fold.ne(fold).to_numpy()
                valid = ~train
                if set(data.loc[train, "feature_group"]) & set(data.loc[valid, "feature_group"]):
                    raise ValueError("Group leakage in frozen fold")
                model = make_candidate(model_name, seed, device, y[train])
                model.fit(x.loc[train], y[train])
                predictions[valid] = model.predict_proba(x.loc[valid])[:, 1]
                fold_metric = score(y[valid], predictions[valid])
                fold_rows.append({"model": model_name, "device": device, "seed": seed,
                                  "fold": fold, "train_rows": int(train.sum()),
                                  "train_positives": int(y[train].sum()), **fold_metric})
                for machine in ("cn7", "rg3"):
                    machine_train = train & data.machine.eq(machine).to_numpy()
                    machine_valid = valid & data.machine.eq(machine).to_numpy()
                    machine_positions = np.flatnonzero(machine_valid)
                    top10_count = max(1, int(np.ceil(len(machine_positions) * .1)))
                    top10_positions = machine_positions[
                        np.argsort(-predictions[machine_positions], kind="stable")[:top10_count]]
                    top10 = np.zeros(len(data), dtype=bool)
                    top10[top10_positions] = True
                    for condition in CONDITIONS:
                        boundary = float(data.loc[machine_train, condition].median())
                        for side, mask in (("le_train_median", data[condition].le(boundary).to_numpy()),
                                           ("gt_train_median", data[condition].gt(boundary).to_numpy())):
                            selection = machine_valid & mask
                            if selection.sum() == 0:
                                continue
                            condition_rows.append({"model": model_name, "device": device,
                                                   "seed": seed, "fold": fold, "machine": machine,
                                                   "condition": condition, "side": side,
                                                   "train_median": boundary, "rows": int(selection.sum()),
                                                   "label1": int(y[selection].sum()),
                                                   "mean_score": float(predictions[selection].mean()),
                                                   "top10_count": int((selection & top10).sum()),
                                                   "top10_true_positive": int((selection & top10 & (y == 1)).sum()),
                                                   "top10_false_positive": int((selection & top10 & (y == 0)).sum()),
                                                   "top10_false_negative": int((selection & ~top10 & (y == 1)).sum())})
            if not np.isfinite(predictions).all():
                raise RuntimeError("OOF prediction coverage incomplete")
            base = data[["machine", mg.ID_COL, "feature_group", "outer_fold"]].rename(
                columns={mg.ID_COL: "source_row_id"}).copy()
            base["label_value"] = y
            base["score"] = predictions
            base["model"] = model_name
            base["device"] = device
            base["seed"] = seed
            prediction_rows.append(base)
            for machine in ("all", "cn7", "rg3"):
                mask = np.ones(len(data), dtype=bool) if machine == "all" else data.machine.eq(machine).to_numpy()
                metric_rows.append({"model": model_name, "device": device, "seed": seed,
                                    "machine": machine, **score(y[mask], predictions[mask])})
            print(f"{model_name} seed={seed} complete", flush=True)
    predictions = pd.concat(prediction_rows, ignore_index=True)
    metrics = pd.DataFrame(metric_rows)
    folds = pd.DataFrame(fold_rows)
    conditions = pd.DataFrame(condition_rows)
    predictions.to_csv(output / "oof_predictions.csv", index=False)
    metrics.to_csv(output / "metrics_by_seed_machine.csv", index=False)
    folds.to_csv(output / "metrics_by_fold.csv", index=False)
    conditions.to_csv(output / "condition_slices.csv", index=False)
    mean = metrics.groupby(["model", "device", "machine"], as_index=False)[
        ["average_precision", "roc_auc", "top10_recall", "top20_recall",
         "brier_unadjusted", "log_loss_unadjusted"]].agg(["mean", "std"])
    mean.columns = ["_".join(str(piece) for piece in name if piece) if isinstance(name, tuple) else name
                    for name in mean.columns]
    mean.to_csv(output / "comparison_summary.csv", index=False)
    manifest = {
        "status": "complete_development_oof_not_independent_holdout", "device": device,
        "started_at_utc": started, "finished_at_utc": datetime.now(timezone.utc).isoformat(),
        "source_scope": "frozen development partition only; previous holdout not evaluated",
        "frozen_manifest_sha256": mg.sha256(cd.FROZEN / "split_manifest.csv"),
        "source_files": provenance, "development_rows": len(data),
        "development_groups": int(data.feature_group.nunique()),
        "development_label1": int(y.sum()), "folds": sorted(data.outer_fold.unique().tolist()),
        "seeds": SEEDS, "models": models, "feature_columns": list(x.columns),
        "exact_feature_group_leakage": 0, "label_semantics_confirmed": False,
        "early_prediction_evaluated": False, "temporal_dl_eligible": False,
        "upstream_scaling_and_temporal_independence_verified": False,
        "gpu_receipt": gpu_receipt, "gpu_runtime": gpu_runtime,
        "caveat": "Post-selection development analysis; scores for numeric label 1, not validated defect probability. Class weighting distorts raw calibration. Small positive count, especially RG3. No claim of prospective generalization.",
        "code_sha256": mg.sha256(Path(__file__)),
        "packages": {name: importlib.metadata.version(name) for name in
                     ("numpy", "pandas", "scikit-learn", "catboost", "lightgbm", "xgboost")},
        "python": sys.version, "platform": platform.platform(),
    }
    write_json(output / "run_manifest.json", manifest)
    write_json(output / "artifact_hashes.json", {p.name: mg.sha256(p) for p in sorted(output.iterdir()) if p.is_file()})
    print(f"complete: {output}", flush=True)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--device", choices=("cpu", "gpu"), required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--task04-receipt", type=Path)
    args = parser.parse_args()
    output = args.output_dir.resolve()
    if not output.is_relative_to(ROOT / "outputs"):
        parser.error("Output must be a new directory below outputs/")
    run(args.device, output, args.task04_receipt)


if __name__ == "__main__":
    main()
